### PR TITLE
Granular scope

### PR DESCRIPTION
**Pull request by mammique**
Hi, I've  sent a patch for a more granular scope this summer, it is  described @ https://github.com/hiidef/oauth2app/issues/1

### CODE REVIEW

**Comment by wehriam** [comment]
Hi Mammique - thanks for the help on the app. I'm taking a look now.

**Comment by wehriam** [comment]
Sorry for not getting back to you sooner. On reading the spec: 

http://tools.ietf.org/html/draft-ietf-oauth-v2-23#page-21

> The value of the scope parameter is expressed as a list of space-
> delimited, case sensitive strings.  The strings are defined by the
> authorization server.  If the value contains multiple space-delimited
> strings, their order does not matter, and each string adds an
> additional access range to the requested scope.

In it's current incarnation, a request will be authenticated if it's credentials meet or exceed that of the requested resource. You can provide multiple scopes, for example access to "email," "password," and "last_name" to provide granularity.

If a resource requires the "email" and "password" access ranges and the access token has "email," "password," and "last_name" access, the request will be granted. If the access token only has a subset of those access_ranges, the request will be denied.

Granular scope is provided through multiple access ranges. 

Thanks again for the contribution, and please let me know if I have misunderstood your intent. You can reach me at johnwehr@hiidef.com if you have any questions.

**Comment by mammique** [comment]
Hi John, thanks for your answer.

Yes, I understand how this works in its current incarnation, I'm not suggesting to change that. Maybe my definition of "granular" is not appropriate for my proposal. What I propose is just to add another optional scope range check, in the case (my case) we don't want to deny access to someone requesting a lower scope range, but just knowing which scopes are met and provide a response accordingly, instead of rejecting.

E.g. if the user requests "email" and "password" but only have access to "email", we provide a response with only the "email" field. This can be done by initializing a Authenticator() with scope_match='intersect' attribute, then read the authorized_scope_intersect property.

Don't you think this would be an interesting feature?

Thanks,

Camille.

**Comment by wehriam** [comment]
Ah, I see - you're saying it could offer different results based on various access ranges.

This seems external to the oAuth 2 spec, which only covers a different response when no scope parameter is included with the request:

> If the client omits the scope parameter when requesting
> authorization, the authorization server MUST either process the
> request using a pre-defined default value, or fail the request
> indicating an invalid scope.

This would be best implemented by subclassing the reference oAuth 2 implementation classes.

**Comment by mammique** [comment]
I see, I didn't remember this was covered by the RFC. I'll trying subclassing on next update.

Thanks!

Camille.

**Pull request closed without merging**
